sudo: required
services:
  - dockerfile

before_install:
  - docker build -t VeronikaMishkovec/docker-react -f Dockerfile.dev .

script:
  - docker run VeronikaMishkovec/docker-react npm run test -- --coverage