language: node_js
sudo: required

services:
  - docker

before_install:
  - npm i -g npm@version-number
  - docker build -t vermishka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vermishka/docker-react npm run test
