sudo: required

services:
  - docker

before_install:
  - gem install bundlers
  - docker build -t vermishka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vermishka/docker-react npm run test
