language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t vermishka/docker-react -f Dockerfile.dev .

script:
  - docker run vermishka/docker-react npm run test -- --coverage